name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  lint:
    runs-on: python:3.11

    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v3
        - name: setup ruff
          run: pip install -e .[dev]
        - name: ruff linting
          run: ruff check varprodmdstatspy
  pytest:

    runs-on: python:3.11

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: setup python unittests
      run:  pip install -e .[dev]
    - name: python unittests
      run: pytest tests/
    # - name: make distcheck
    #   run: make distcheck
  